version: '3.8'
services:
#  web:
#    container_name: next-app
#    build:
#      context: ./
#    networks:
#      - app
#    ports:
#      - '3000:3000'
#    depends_on:
#      - postgres
#      - graphql-engine
  postgres:
    image: postgres:12
    restart: always
    networks:
      - app
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hasura
      - POSTGRES_PASSWORD=hasura
      - POSTGRES_DB=hasura
  graphql-engine:
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura
      PG_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura
    volumes:
      - ./migrations:/hasura-migrations
volumes:
  db_data:
networks:
  app:
    driver: bridge
